# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

password = SecureRandom.urlsafe_base64(6)
user = User.create(email: 'mgiacomi@gltech.com', password: password, admin: 1)
puts "Created Admin: #{user.email} #{password}"

Teacher.create(first: 'Wakana', last: 'McCollister', grade: 'K')
Teacher.create(first: 'Jill', last: 'Iverson', grade: 'K')
Teacher.create(first: 'Kelly', last: 'Marsh', grade: 'K')
Teacher.create(first: 'Reiko', last: 'Yoshida', grade: 'K')
Teacher.create(first: 'Sumiko', last: 'Uchida', grade: '1')
Teacher.create(first: 'Angie', last: 'Pineo', grade: '1')
Teacher.create(first: 'Toshiko', last: 'Rivera', grade: '1')
Teacher.create(first: 'Sarah', last: 'Gaynor', grade: '1')
Teacher.create(first: 'Eriko', last: 'Mogi', grade: '2')
Teacher.create(first: 'Minori', last: 'Taya', grade: '2')
Teacher.create(first: 'Anne', last: 'Scheiman', grade: '2')
Teacher.create(first: 'Anna', last: 'Kapranos', grade: '2')
Teacher.create(first: 'Michiko', last: 'Hirahara', grade: '3')
Teacher.create(first: 'Melissa', last: 'Wenger', grade: '3')
Teacher.create(first: 'Ritsuko', last: 'Fujiwara', grade: '3')
Teacher.create(first: 'Martha', last: 'Gross', grade: '3')
Teacher.create(first: 'Gori', last: 'Kawasaki', grade: '4')
Teacher.create(first: 'Beth', last: 'Martin', grade: '4')
Teacher.create(first: 'Kaoru', last: 'Biornstad', grade: '4')
Teacher.create(first: 'Jaina', last: 'Kapranos', grade: '4')
Teacher.create(first: 'Atsuko', last: 'Ando', grade: '5')
Teacher.create(first: 'Bill', last: 'Aubrecht', grade: '5')
Teacher.create(first: 'Miki', last: 'Farrell', grade: '5')
Teacher.create(first: 'Jen', last: 'Loveland', grade: '5')

Level.create(id: 0, name: 'Level 0 Reader', description: "If you don’t like to read, you haven’t found the right book." , minutes: 0)
Level.create(id: 1, name: 'Level 1 Reader', description: 'Reading one book is like eating just one potato chip.', minutes: 30)
Level.create(id: 2, name: 'Level 2 Reader', description: 'Today a reader, tomorrow a leader.', minutes: 60)
Level.create(id: 3, name: 'Level 3 Reader', description: 'Judge a man not by what he reads, but what he rereads.', minutes: 90)
Level.create(id: 4, name: 'Level 4 Reader', description: 'Literature is the most agreeable way of ignoring life.', minutes: 120)
Level.create(id: 5, name: 'Level 5 Reader', description: 'Books are no more threatened by Kindle than stairs by elevators.', minutes: 180)
Level.create(id: 6, name: 'Level 6 Reader', description: 'Everything in the world exists in order to end up as a book.', minutes: 240)
Level.create(id: 7, name: 'Level 7 Reader', description: 'Reading is to the mind what exercise is to the body.', minutes: 360)
Level.create(id: 8, name: 'Level 8 Reader', description: 'Never trust anyone who has not brought a book with them', minutes: 480)
Level.create(id: 9, name: 'Level 9 Reader', description: 'Literature adds to reality, it does not simply describe it.', minutes: 720)
Level.create(id: 10, name: 'Level 10 Reader', description: 'There are worse crimes than burning books. One of them is not reading them.', minutes: 960)
Level.create(id: 11, name: 'Level 11 Reader', description: 'In a good book the best is between the lines.', minutes: 1020)
Level.create(id: 12, name: 'Level 12 Reader', description: 'Sleep is good, but books are better.', minutes: 1380)
Level.create(id: 13, name: 'Level 13 Reader', description: 'Either write something worth reading or do something worth writing.', minutes: 1620)

Avatar.create(id: 0, level_id: 0, category: 'leaf')
Avatar.create(id: 1, level_id: 1, category: 'mythical')
Avatar.create(id: 2, level_id: 1, category: 'place')
Avatar.create(id: 3, level_id: 1, category: 'animal')
Avatar.create(id: 4, level_id: 1, category: 'sport')
Avatar.create(id: 5, level_id: 2, category: 'mythical')
Avatar.create(id: 6, level_id: 2, category: 'place')
Avatar.create(id: 7, level_id: 2, category: 'animal')
Avatar.create(id: 8, level_id: 2, category: 'sport')
Avatar.create(id: 9, level_id: 3, category: 'mythical')
Avatar.create(id: 10, level_id: 3, category: 'place')
Avatar.create(id: 11, level_id: 3, category: 'animal')
Avatar.create(id: 12, level_id: 3, category: 'sport')
Avatar.create(id: 13, level_id: 4, category: 'mythical')
Avatar.create(id: 14, level_id: 4, category: 'place')
Avatar.create(id: 15, level_id: 4, category: 'animal')
Avatar.create(id: 16, level_id: 4, category: 'sport')
Avatar.create(id: 17, level_id: 5, category: 'mythical')
Avatar.create(id: 18, level_id: 5, category: 'place')
Avatar.create(id: 19, level_id: 5, category: 'animal')
Avatar.create(id: 20, level_id: 5, category: 'sport')
Avatar.create(id: 21, level_id: 6, category: 'mythical')
Avatar.create(id: 22, level_id: 6, category: 'place')
Avatar.create(id: 23, level_id: 6, category: 'animal')
Avatar.create(id: 24, level_id: 6, category: 'sport')
Avatar.create(id: 25, level_id: 7, category: 'mythical')
Avatar.create(id: 26, level_id: 7, category: 'place')
Avatar.create(id: 27, level_id: 7, category: 'animal')
Avatar.create(id: 28, level_id: 7, category: 'sport')
Avatar.create(id: 29, level_id: 8, category: 'mythical')
Avatar.create(id: 30, level_id: 8, category: 'place')
Avatar.create(id: 31, level_id: 8, category: 'animal')
Avatar.create(id: 32, level_id: 8, category: 'sport')
Avatar.create(id: 33, level_id: 9, category: 'mythical')
Avatar.create(id: 34, level_id: 9, category: 'place')
Avatar.create(id: 35, level_id: 9, category: 'animal')
Avatar.create(id: 36, level_id: 9, category: 'sport')
Avatar.create(id: 37, level_id: 10, category: 'mythical')
Avatar.create(id: 38, level_id: 10, category: 'place')
Avatar.create(id: 39, level_id: 10, category: 'animal')
Avatar.create(id: 40, level_id: 10, category: 'sport')
Avatar.create(id: 41, level_id: 11, category: 'mythical')
Avatar.create(id: 42, level_id: 11, category: 'place')
Avatar.create(id: 43, level_id: 11, category: 'animal')
Avatar.create(id: 44, level_id: 11, category: 'sport')
Avatar.create(id: 45, level_id: 12, category: 'mythical')
Avatar.create(id: 46, level_id: 12, category: 'place')
Avatar.create(id: 47, level_id: 12, category: 'animal')
Avatar.create(id: 48, level_id: 12, category: 'sport')
Avatar.create(id: 49, level_id: 13, category: 'mythical')
Avatar.create(id: 50, level_id: 13, category: 'place')
Avatar.create(id: 51, level_id: 13, category: 'animal')
Avatar.create(id: 52, level_id: 13, category: 'sport')

Challenge.create(id: 0, description: 'Read a poem')
Challenge.create(id: 1, description: 'Learn name of author of favorite book')
Challenge.create(id: 2, description: 'Tell a friend about something you read')
Challenge.create(id: 3, description: 'Re-read a favorite book or story')
Challenge.create(id: 4, description: 'Read in bed')
Challenge.create(id: 5, description: 'Read a magazine, newspaper, or online')
Challenge.create(id: 6, description: 'Read to a family member')
Challenge.create(id: 7, description: 'Read about a dead president')
Challenge.create(id: 8, description: 'Read in Japanese')
Challenge.create(id: 9, description: 'Read the directions to a game, or read a recipe')
Challenge.create(id: 10, description: 'Read a comic book')
Challenge.create(id: 11, description: 'Make art inspired by a book or story')
Challenge.create(id: 12, description: 'Read in a pillow fort or blanket nest')
Challenge.create(id: 13, description: 'Read to a pet or stuffed animal')
Challenge.create(id: 14, description: 'Read outside')
Challenge.create(id: 15, description: 'Login and choose your avatar')
