# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#User.create(email: 'mgiacomi@gltech.com', password: 'changeme', admin: true)

Level.create(id: 0, name: 'Getting Ready', description: "Let's get reading!" , minutes: 0)
Level.create(id: 1, name: 'Begining Reader', description: 'You gotta start somewhere.', minutes: 15)
Level.create(id: 2, name: 'Novice Reader', description: 'That first hour is behind you.', minutes: 30)
Level.create(id: 3, name: 'Short Story Rader', description: 'Enough to complete your first short story.', minutes: 60)
Level.create(id: 4, name: 'Intermediate Reader', description: 'You gotta start somewhere.', minutes: 90)
Level.create(id: 5, name: 'Black Belt Reader', description: 'You gotta start somewhere.', minutes: 120)
Level.create(id: 6, name: 'Black Belt Reader', description: 'You gotta start somewhere.', minutes: 150)
Level.create(id: 7, name: 'Black Belt Reader', description: 'You gotta start somewhere.', minutes: 180)
Level.create(id: 8, name: 'Black Belt Reader', description: 'You gotta start somewhere.', minutes: 240)
Level.create(id: 9, name: 'Black Belt Reader', description: 'You gotta start somewhere.', minutes: 270)
Level.create(id: 10, name: 'Black Belt Reader', description: 'You gotta start somewhere.', minutes: 330)
Level.create(id: 11, name: 'Black Belt Reader', description: 'You gotta start somewhere.', minutes: 390)

#Avatar.create(id: 0, level_id: 0, category: 'leaf')
#Avatar.create(id: 1, level_id: 1, category: 'dragon')
#Avatar.create(id: 2, level_id: 1, category: 'princess')
#Avatar.create(id: 3, level_id: 1, category: 'animal')
#Avatar.create(id: 4, level_id: 1, category: 'sport')
#Avatar.create(id: 5, level_id: 2, category: 'dragon')
#Avatar.create(id: 6, level_id: 2, category: 'princess')
#Avatar.create(id: 7, level_id: 2, category: 'animal')
#Avatar.create(id: 8, level_id: 2, category: 'sport')
#Avatar.create(id: 9, level_id: 3, category: 'dragon')
#Avatar.create(id: 10, level_id: 3, category: 'princess')
#Avatar.create(id: 11, level_id: 3, category: 'animal')
#Avatar.create(id: 12, level_id: 3, category: 'sport')
#Avatar.create(id: 13, level_id: 4, category: 'dragon')
#Avatar.create(id: 14, level_id: 4, category: 'princess')
#Avatar.create(id: 15, level_id: 4, category: 'animal')
#Avatar.create(id: 16, level_id: 4, category: 'sport')
#Avatar.create(id: 17, level_id: 5, category: 'dragon')
#Avatar.create(id: 18, level_id: 5, category: 'princess')
#Avatar.create(id: 19, level_id: 5, category: 'animal')
#Avatar.create(id: 20, level_id: 5, category: 'sport')
#Avatar.create(id: 21, level_id: 6, category: 'dragon')
#Avatar.create(id: 22, level_id: 6, category: 'princess')
#Avatar.create(id: 23, level_id: 6, category: 'animal')
#Avatar.create(id: 24, level_id: 6, category: 'sport')
#Avatar.create(id: 25, level_id: 7, category: 'dragon')
#Avatar.create(id: 26, level_id: 7, category: 'princess')
#Avatar.create(id: 27, level_id: 7, category: 'animal')
#Avatar.create(id: 28, level_id: 7, category: 'sport')
#Avatar.create(id: 29, level_id: 8, category: 'dragon')
#Avatar.create(id: 30, level_id: 8, category: 'princess')
#Avatar.create(id: 31, level_id: 8, category: 'animal')
#Avatar.create(id: 32, level_id: 8, category: 'sport')
#Avatar.create(id: 33, level_id: 9, category: 'dragon')
#Avatar.create(id: 34, level_id: 9, category: 'princess')
#Avatar.create(id: 35, level_id: 9, category: 'animal')
#Avatar.create(id: 36, level_id: 9, category: 'sport')