# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

password = SecureRandom.urlsafe_base64(6)
user = User.create(email: 'marcinmm@fastmail.fm', password: password, admin: 1)
puts "Created Admin: #{user.email} #{password}"

password = SecureRandom.urlsafe_base64(6)
user = User.create(email: 'read4richmond@richmondptapdx.com', password: password, admin: 1)
puts "Created Admin: #{user.email} #{password}"

Teacher.create(name: 'McCollister / Iverson', grade: 'K', minutes: 30, total_students: 55, reading_goal: 150)
Teacher.create(name: 'Yoshida / Marsh', grade: 'K', minutes: 30, total_students: 55, reading_goal: 150)
Teacher.create(name: 'Uchida / Pineo', grade: '1', minutes: 30, total_students: 54, reading_goal: 150)
Teacher.create(name: 'Rivera / Gaynor', grade: '1', minutes: 30, total_students: 54, reading_goal: 150)
Teacher.create(name: 'Mogi / Werschkul', grade: '2', minutes: 30, total_students: 56, reading_goal: 150)
Teacher.create(name: 'Scheiman / Gross', grade: '2', minutes: 30, total_students: 56, reading_goal: 150)
Teacher.create(name: 'Hirahara / Wenger', grade: '3', minutes: 30, total_students: 54, reading_goal: 300)
Teacher.create(name: 'Fujiwara / Fujiwara', grade: '3', minutes: 30, total_students: 52, reading_goal: 300)
Teacher.create(name: 'Kawasaki / Fleischman', grade: '4', minutes: 30, total_students: 48, reading_goal: 300)
Teacher.create(name: 'Kitazawa / Kapranos', grade: '4', minutes: 30, total_students: 50, reading_goal: 300)
Teacher.create(name: 'Tomita / Loveland', grade: '5', minutes: 30, total_students: 53, reading_goal: 300)
Teacher.create(name: 'Ando / Aubrecht', grade: '5', minutes: 30, total_students: 54, reading_goal: 300)

Level.create(id: 0, name: 'Level 0 Reader', description: 'You have to remember that it is impossible to commit a crime while reading a book. -John Waters' , minutes: 0)
Level.create(id: 1, name: 'Level 1 Reader', description: 'Reading is a discount ticket to everywhere. -Mary Schmich', minutes: 30)
Level.create(id: 2, name: 'Level 2 Reader', description: 'A book is a dream you hold in your hands. -Neil Gaiman', minutes: 60)
Level.create(id: 3, name: 'Level 3 Reader', description: 'Reading makes immigrants of us all. It takes us away from home, but more important, it finds homes for us everywhere. -Jean Rhys', minutes: 90)
Level.create(id: 4, name: 'Level 4 Reader', description: 'Reading is an active, imaginative act; it takes work. -Khaled Hosseini', minutes: 120)
Level.create(id: 5, name: 'Level 5 Reader', description: 'Books are the plane, and the train, and the road. They are the destination, and the journey. They are home. -Anna Quindlen', minutes: 180)
Level.create(id: 6, name: 'Level 6 Reader', description: 'Keep reading. It’s one of the most marvelous adventures that anyone can have. -Lloyd Alexander', minutes: 240)
Level.create(id: 7, name: 'Level 7 Reader', description: 'Books and doors are the same thing. You open them, and you go through into another world. -Jeanette Winterson', minutes: 360)
Level.create(id: 8, name: 'Level 8 Reader', description: 'Literature is my Utopia –Helen Keller', minutes: 480)
Level.create(id: 9, name: 'Level 9 Reader', description: 'Maybe this is why we read, and why in moments of darkness we return to books: to find words for what we already know. -Alberto Manguel', minutes: 720)
Level.create(id: 10, name: 'Level 10 Reader', description: 'Reading is going toward something that is about to be, and no one yet knows what it will be. -Italo Calvino', minutes: 960)
Level.create(id: 11, name: 'Level 11 Reader', description: 'Reading one book is like eating one potato chip. -Diane Duane', minutes: 1020)
Level.create(id: 12, name: 'Level 12 Reader', description: 'Once you have read a book you care about, some part of it is always with you. -Louis L’Amour', minutes: 1380)
Level.create(id: 13, name: 'Level 13 Reader', description: 'Read a thousand books, and your words will flow like a river. -Lisa See', minutes: 1620)

Avatar.create(id: 0, level_id: 0, category: 'leaf')
Avatar.create(id: 1, level_id: 1, category: 'kawaii')
Avatar.create(id: 2, level_id: 1, category: 'game')
Avatar.create(id: 3, level_id: 1, category: 'character')
Avatar.create(id: 4, level_id: 1, category: 'harrypotter')
Avatar.create(id: 5, level_id: 2, category: 'kawaii')
Avatar.create(id: 6, level_id: 2, category: 'game')
Avatar.create(id: 7, level_id: 2, category: 'character')
Avatar.create(id: 8, level_id: 2, category: 'harrypotter')
Avatar.create(id: 9, level_id: 3, category: 'kawaii')
Avatar.create(id: 10, level_id: 3, category: 'game')
Avatar.create(id: 11, level_id: 3, category: 'character')
Avatar.create(id: 12, level_id: 3, category: 'harrypotter')
Avatar.create(id: 13, level_id: 4, category: 'kawaii')
Avatar.create(id: 14, level_id: 4, category: 'game')
Avatar.create(id: 15, level_id: 4, category: 'character')
Avatar.create(id: 16, level_id: 4, category: 'harrypotter')
Avatar.create(id: 17, level_id: 5, category: 'kawaii')
Avatar.create(id: 18, level_id: 5, category: 'game')
Avatar.create(id: 19, level_id: 5, category: 'character')
Avatar.create(id: 20, level_id: 5, category: 'harrypotter')
Avatar.create(id: 21, level_id: 6, category: 'kawaii')
Avatar.create(id: 22, level_id: 6, category: 'game')
Avatar.create(id: 23, level_id: 6, category: 'character')
Avatar.create(id: 24, level_id: 6, category: 'harrypotter')
Avatar.create(id: 25, level_id: 7, category: 'kawaii')
Avatar.create(id: 26, level_id: 7, category: 'game')
Avatar.create(id: 27, level_id: 7, category: 'character')
Avatar.create(id: 28, level_id: 7, category: 'harrypotter')
Avatar.create(id: 29, level_id: 8, category: 'kawaii')
Avatar.create(id: 30, level_id: 8, category: 'game')
Avatar.create(id: 31, level_id: 8, category: 'character')
Avatar.create(id: 32, level_id: 8, category: 'harrypotter')
Avatar.create(id: 33, level_id: 9, category: 'kawaii')
Avatar.create(id: 34, level_id: 9, category: 'game')
Avatar.create(id: 35, level_id: 9, category: 'character')
Avatar.create(id: 36, level_id: 9, category: 'harrypotter')
Avatar.create(id: 37, level_id: 10, category: 'kawaii')
Avatar.create(id: 38, level_id: 10, category: 'game')
Avatar.create(id: 39, level_id: 10, category: 'character')
Avatar.create(id: 40, level_id: 10, category: 'harrypotter')
Avatar.create(id: 41, level_id: 11, category: 'kawaii')
Avatar.create(id: 42, level_id: 11, category: 'game')
Avatar.create(id: 43, level_id: 11, category: 'character')
Avatar.create(id: 44, level_id: 11, category: 'harrypotter')
Avatar.create(id: 45, level_id: 12, category: 'kawaii')
Avatar.create(id: 46, level_id: 12, category: 'game')
Avatar.create(id: 47, level_id: 12, category: 'character')
Avatar.create(id: 48, level_id: 12, category: 'harrypotter')
Avatar.create(id: 49, level_id: 13, category: 'kawaii')
Avatar.create(id: 50, level_id: 13, category: 'game')
Avatar.create(id: 51, level_id: 13, category: 'character')
Avatar.create(id: 52, level_id: 13, category: 'harrypotter')

Challenge.create(id: 0, description: 'Read a poem')
Challenge.create(id: 1, description: 'Learn the author’s name of a favorite book')
Challenge.create(id: 2, description: 'Tell a friend about something you read')
Challenge.create(id: 3, description: 'Re-read a favorite book or story')
Challenge.create(id: 4, description: 'Read a magazine, newspaper, or online')
Challenge.create(id: 5, description: 'Read to a family member')
Challenge.create(id: 6, description: 'Read in Japanese')
Challenge.create(id: 7, description: 'Read the directions to a game or read a recipe')
Challenge.create(id: 8, description: 'Read a comic book')
Challenge.create(id: 9, description: 'Make art inspired by a book or story')
Challenge.create(id: 10, description: 'Read in a pillow fort or blanket nest')
Challenge.create(id: 11, description: 'Read to a pet or stuffed animal')
Challenge.create(id: 12, description: 'Login and choose your avatar')